### ISSUE TITLE
is there any way to make this work on windows

### ISSUE THREAD

**Issue by ultraleetj** [amo13/spleeter-wrapper#4]
I tried to use this on windows using the wsl subsystem but encounter a few errors when I try to run just the script, I get the following output

splw.sh: line 2: $'\r': command not found
splw.sh: line 17: $'\r': command not found
splw.sh: line 19: conda: command not found
: No such file or directory
splw.sh: line 22: conda: command not found
splw.sh: line 23: $'\r': command not found
splw.sh: line 25: $'\r': command not found
splw.sh: line 37: $'\r': command not found
splw.sh: line 39: syntax error near unexpected token `$'{\r''
'plw.sh: line 39: `show_help() {

if this is normal and I just need to run this over a file then its fine, if not, do you know any other way I could use this, or if someone also came up with a solution to separate files longer than 10 minutes using spleet

**Comment by amo13** [comment]
Looks like you need to set up an anaconda distribution.
For the issue with the carriage return \r though, I don't know. Unfortunately, since I decided to switch to linux a long time ago, I am of no help on windows any more... My dumb suggestion is therefore: try this on linux. Install it persistently on a usb drive like it was a hard drive and use it for stuff like that.

**Comment by ultraleetj** [comment]
hi, well I think I solved this because I needed to process a half an
hour file but the solution is not at all elegant... I have a 32 gb ram
machine and what I did was to increase the size of the page file in
windows using the advanced system configuration to 35 gb. That did it.
still, no major crash or anything but I would have loved to use this
none the less. Thanks for the quick response.

2022-05-12 1:32 GMT-05:00, amo13 ***@***.***>:
